name: Github Page Action

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  numpy-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Login to Huggingface
        run: python -c "import huggingface_hub; huggingface_hub.login('${{secrets.HF_TOKEN}}', add_to_git_credential=True)"
      - name: Run Python
        run: python main.py
